package uniandes.cumbia.bpel.elements.exit;

import uniandes.cumbia.openobjects.elements.OpenObject;
import uniandes.cumbia.openobjects.execution.events.generators.EventGenerator;
import uniandes.cumbia.openobjects.execution.instance.ModelInstance;


public abstract class AbstractExit extends OpenObject implements IExit
{

    // -----------------------------------------------------------------
    // Constants
    // -----------------------------------------------------------------
    
    private static final String EXIT = "exit";
    
    private static final String REINIT = "reInit";
    
    // -----------------------------------------------------------------
    // Attributes
    // -----------------------------------------------------------------
    
    /**
     * Generator of the event finalize
     */
    private EventGenerator generatorExit;
    
    /**
     * Generator of the event reInit
     */
    private EventGenerator generatorReInit;
    
    
    // -----------------------------------------------------------------
    // Methods
    // -----------------------------------------------------------------
    
    /**
     * 
     */
    public AbstractExit( ModelInstance modelInstance, String elementName, String typeName )
    {
        super( modelInstance, elementName, typeName );
    }
    
    /**
     * 
     */
    public AbstractExit( ModelInstance modelInstance, String elementName )
    {
        super( modelInstance, elementName, TYPE_EXIT);
    }
    

    // -----------------------------------------------------------------
    // Methods
    // -----------------------------------------------------------------
    
    /**
     * This method registers in the EventsManager of the element, all the events that are generated by this entity.<br>
     * This method also creates the generators for the entity's events
     */
    public void registerGeneratedEvents()
    {
        generatorExit = createAndRegisterEventGenerator(EXIT);
        generatorReInit = createAndRegisterEventGenerator( REINIT );
    }
    

    
    /**
     * Returns the count of the elements. This helps to figure out the amount of elements inside elements like a scope or a flow
     * @return the amount of elements inside the element
     */
    public int getElementCount( )
    {
        return 1;
    }


    /**
     * Generates the activate event
     */
    protected void exitExit( )
    {
        generatorExit.generate( );
    }
    

    /**
     * Fires the reInit event
     */
    protected void reInitExit()
    {
        generatorReInit.generate( );
    }

}
