/*******************************************************************************
 * $Id: IEngineEventListener.java,v 1.1 2009/01/29 21:38:43 man-muno Exp $
 * 
 * Proyecto Cumbia
 * (http://agamenon.uniandes.edu.co/~csw)
 * 
 * Grupo de Investigacion en Construccion de Software
 * Departamento de Ingenieria de Sistemas y Computacion
 * Universidad de los Andes
 * Bogota - Colombia
 * 
 * Copyright (c) 2008
 * Todos los derechos reservados. 
 * 
 *******************************************************************************/
package uniandes.cumbia.bpel.engine.events;

import java.io.Serializable;

/**
 * This is the interface that should be implemented by all the classes that whish to receive notifications about high-level events generated by the engine
 */
public interface IEngineEventListener extends Serializable
{
    /**
     * This method is called when an event is received
     * @param event The event that generated the notification
     */
    void receiveEvent( IEvent event );

}
