/*******************************************************************************
 * $Id: IEvent.java,v 1.1 2009/01/29 21:38:43 man-muno Exp $
 * 
 * Proyecto Cumbia
 * (http://agamenon.uniandes.edu.co/~csw)
 * 
 * Grupo de Investigacion en Construccion de Software
 * Departamento de Ingenieria de Sistemas y Computacion
 * Universidad de los Andes
 * Bogota - Colombia
 * 
 * Copyright (c) 2008
 * Todos los derechos reservados. 
 * 
 *******************************************************************************/
package uniandes.cumbia.bpel.engine.events;

import java.io.Serializable;

/**
 * This interface is shared by all the High-Level events generated by the engine
 */
public interface IEvent extends Serializable
{
    /**
     * Returns the type of the event
     * @return Int to inform about the type of the event
     */
    int getType( );
}
