package uniandes.cumbia.bpel.elements.pick;

import uniandes.cumbia.openobjects.elements.OpenObject;
import uniandes.cumbia.openobjects.execution.events.generators.EventGenerator;
import uniandes.cumbia.openobjects.execution.instance.ModelInstance;


public abstract class AbstractPick extends OpenObject implements IPick
{
    
    // -----------------------------------------------------------------
    // Constants
    // -----------------------------------------------------------------
    
    private static final String ACTIVATE_PICK = "activate";
    
    private static final String REINIT = "reInit";
    
    // -----------------------------------------------------------------
    // Attributes
    // -----------------------------------------------------------------
    
    /**
     * Generator of the event activate
     */
    private EventGenerator generatorActivate;
    
    /**
     * Generator of the event reInit
     */
    private EventGenerator generatorReInit;
    
    
    // -----------------------------------------------------------------
    // Methods
    // -----------------------------------------------------------------
    
    /**
     * 
     */
    public AbstractPick( ModelInstance modelInstance, String elementName, String typeName )
    {
        super( modelInstance, elementName, typeName );
    }
    
    /**
     * 
     */
    public AbstractPick( ModelInstance modelInstance, String elementName )
    {
        super( modelInstance, elementName, TYPE_PICK);
    }
    
    
    /**
     * This method registers in the EventsManager of the element, all the events that are generated by this entity.<br>
     * This method also creates the generators for the entity's events
     */
    public void registerGeneratedEvents()
    {
        generatorActivate = createAndRegisterEventGenerator(ACTIVATE_PICK);
        generatorReInit = createAndRegisterEventGenerator( REINIT );
    }
    
    protected void activatePick()
    {
        generatorActivate.generate( );
    }
    
    protected void reInitPick()
    {
        generatorReInit.generate( );
    }
}
