/*******************************************************************************
 * $Id: InstanceSensorAdmin.java,v 1.1 2009/01/29 21:38:43 man-muno Exp $
 * 
 * Proyecto Cumbia
 * (http://agamenon.uniandes.edu.co/~csw)
 * 
 * Grupo de Investigaci�n en Construcci�n de Software
 * Departamento de Ingenier�a de Sistemas y Computaci�n
 * Universidad de los Andes
 * Bogot� - Colombia
 * 
 * Copyright (c) 2008
 * Todos los derechos reservados. 
 * 
 *******************************************************************************/
package uniandes.cumbia.bpel.instance;

import uniandes.cumbia.bpel.engine.events.SensorAdmin;

/**
 * This class manages the high level events generated by an instance space
 */
public class InstanceSensorAdmin extends SensorAdmin
{

	// -----------------------------------------------------------------
	// Constants
	// -----------------------------------------------------------------

	public static final int INSTANCE_STARTED = 1;

	public static final int INSTANCE_ENDED = 2;

	public static final int INSTANCE_SUSPENDED = 3;

	// -----------------------------------------------------------------
	// Attributes
	// -----------------------------------------------------------------

	private int instanceId;

	// -----------------------------------------------------------------
	// Methods
	// -----------------------------------------------------------------

	/**
	 * Builds the events manager
	 */
	public InstanceSensorAdmin()
	{
		super();
	}

	public int getInstanceId()
	{
		return instanceId;
	}

	public void setInstanceId(int instanceId)
	{
		this.instanceId = instanceId;
	}

}
