/*******************************************************************************
 * $Id: IEvent.java,v 1.2 2008/11/12 19:42:11 man-muno Exp $
 * 
 * Proyecto Cumbia
 * (http://agamenon.uniandes.edu.co/~csw)
 * 
 * Grupo de Investigación en Construcción de Software
 * Departamento de Ingeniería de Sistemas y Computación
 * Universidad de los Andes
 * Bogotá - Colombia
 * 
 * Copyright (c) 2008
 * Todos los derechos reservados. 
 * 
 *******************************************************************************/
package uniandes.cumbia.bpel.engine.events;

import java.io.Serializable;

/**
 * This interface is shared by all the High-Level events generated by the engine
 */
public interface IEvent extends Serializable
{
    /**
     * Returns the type of the event
     * @return Int to inform about the type of the event
     */
    int getType( );
}
