package fml.tum.model.statemachine;

public enum State {
	IDLE, SHOWING_COMMAND,GOING_TO_LOCATION,GOING_TO_SHELF,GOING_TO_COLUMN,PICKED_UP_PALLET,DROPPED_PALLET, SETTING_MAST_ANGLE, SETTING_MAST_HEIGHT, SETTING_SIDE_SHIFT, WAITING_MAST_ANGLE, WAITING_MAST_HEIGHT, WAITING_SIDESHIFT

}
