package fml.tum.model.statemachine;

public enum Trigger {
	SHOW_COMMAND, GO_TO_LOCATION, GO_TO_IDLE, GO_TO_SHELF, GO_TO_COLUMN,  PICK_UP_PALLET, DROP_PALLET, SET_MAST_ANGLE, SET_MAST_HEIGHT, SET_SIDE_SHIFT, WAIT_MAST_ANGLE, WAIT_MAST_HEIGHT, WAIT_SIDESHIFT

}
