package uniandes.cumbia.bpel.elements.startingPoints;

import uniandes.cumbia.bpel.elements.Interaction;
import uniandes.cumbia.openobjects.execution.events.generators.EventGenerator;
import uniandes.cumbia.openobjects.execution.instance.ModelInstance;

public abstract class AbstractStartingPick extends Interaction implements IStartingPick
{

    // -----------------------------------------------------------------
    // Constants
    // -----------------------------------------------------------------
    
    private static final String ACTIVATE_STARTING_PICK = "activate";
    private static final String MESSAGE_RECEIVED_STARTING_PICK = "messageReceived";

    // -----------------------------------------------------------------
    // Attributes
    // -----------------------------------------------------------------

    /**
     * Generator of the event activate
     */
    private EventGenerator generatorActivate;
    

    /**
     * Generator of the event message received
     */
    private EventGenerator generatorMessageReceived;

    // -----------------------------------------------------------------
    // Constructors
    // -----------------------------------------------------------------

    public AbstractStartingPick( ModelInstance modelInstance, String elementName, String typeName )
    {
        super( modelInstance, elementName, typeName );
    }

    public AbstractStartingPick( ModelInstance modelInstance, String elementName)
    {
        super( modelInstance, elementName, TYPE_STARTING_PICK );
    }
    
    // -----------------------------------------------------------------
    // Methods
    // -----------------------------------------------------------------
    
    /**
     * This method registers in the EventsManager of the element, all the events that are generated by this entity.<br>
     * This method also creates the generators for the entity's events
     */
    public void registerGeneratedEvents( )
    {
        generatorActivate = createAndRegisterEventGenerator( ACTIVATE_STARTING_PICK );
        generatorMessageReceived = createAndRegisterEventGenerator( MESSAGE_RECEIVED_STARTING_PICK );
    }
    
    /**
     * Generates the activated event
     */
    protected void activate()
    {
        generatorActivate.generate( );
    }
    
    /**
     * Generates the message received event
     */
    protected void messageReceived()
    {
        generatorMessageReceived.generate( );
    }
}
